### ISSUE TITLE
Relicense

### ISSUE THREAD

**Issue by challgren** [jomweb/CakeImpersonate#7]
As suggested by https://github.com/FriendsOfCake/awesome-cakephp/pull/316 we should switch to the MIT license. Since there's only 2 contributors to the repo I would be ok with changing to MIT as long as the contributors (@akutaktau  and @challgren) agree. https://github.com/jomweb/CakeImpersonate/graphs/contributors https://www.dropbox.com/s/gomniqg2krkso9k/Screenshot%202019-01-03%2015.46.27.png?dl=0

**Comment by akutaktau** [comment]
Find by me.

**Comment by akutaktau** [comment]
*fine
