### ISSUE TITLE
Api questions

### ISSUE THREAD

**Issue by dereuromark** [jomweb/CakeImpersonate#8]
Shouldnt https://github.com/jomweb/CakeImpersonate/blob/master/src/Controller/Component/ImpersonateComponent.php#L82
be called `isImpersonated()` as the docs also suggest?
isImpersonate() sounds like wrong English to me

and small typo: $userTable should be $usersTable as it is the matching version to UsersTable class (plural).

**Comment by challgren** [comment]
Yes I saw that and was going to deprecate it and add isImpersonated() to correct the spelling. Thank you for the code review! I'll get it updated

**Comment by dereuromark** [comment]
And last but not least there should be a warning in docs to double check that you cannot "spoof" post other users in the controller actions and hijack users accounts you wouldnt/shouldnt have access to.
This can be a common pitfall with such tools, as they circumvent the secure default auth mechanisms.
